services:
    nifi:
        image: 'apache/nifi:1.24.0'
        container_name: nifi_test
        hostname: nifi_test
        environment:
            - NIFI_WEB_HTTP_PORT=8080
        volumes:
            - '~/document/Nifi/shared-directory:/opt/nifi/nifi-current/ls-target'
        ports:
            - '8080:8080'
        networks:
            - big-data-network
    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.4
        container_name: zookeeper_test
        hostname: zookeeper_test
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181
        networks:
            - bigdata-network

    kafka:
        image: confluentinc/cp-kafka:7.4.4
        container_name: kafka_test
        hostname: kafka_test
        depends_on:
            - zookeeper_test
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - "9092:9092"
        networks:
            - bigdata-network
networks:
    big-data-network:
        driver: bridge