services:
    nifi:
        image: 'apache/nifi:1.24.0'
        container_name: nifi_test
        hostname: nifi_test
        environment:
            - NIFI_WEB_HTTP_PORT=8080
        volumes:
            - '~/document/Nifi/shared-directory:/opt/nifi/nifi-current/ls-target'
        ports:
            - '8080:8080'
        networks:
            - big-data-network
networks:
    big-data-network:
        driver: bridge