services:
    nifi:
        image: 'apache/nifi:1.24.0'
        container_name: nifi_test
        hostname: nifi_test
        environment:
            - NIFI_WEB_HTTP_PORT=8080
        volumes:
            - '~/document/Nifi/shared-directory:/opt/nifi/nifi-current/ls-target'
        ports:
            - '8080:8080'
        networks:
            - big-data-network

    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper_test
        hostname: zookeeper_test
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - '2181:2181'
        networks:
            - big-data-network

    kafka:
        image: wurstmeister/kafka:latestls 
        container_name: kafka_test
        hostname: kafka_test
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka_test:9093,OUTSIDE://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper_test:2181
            KAFKA_CREATE_TOPICS: "my-topic:1:1"
        ports:
            - '9092:9092'
        expose:
            - "9093"
        networks:
            - big-data-network

networks:
    big-data-network:
        driver: bridge